language: scala

scala:
   - 2.12.1

script:
- sbt clean coverage test

after_success:
- sbt coverageReport coveralls

jdk: oraclejdk8

services:
  - cassandra

sudo: false

# whitelist
branches:
  only:
    - master
    - develop
